In [1]:
import numpy as np
import tensorflow as tf

In [3]:
import random

In [2]:
#Training data
x_train = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype = float)
y_train = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype = float)

In [4]:
#Trainable variable
w = tf.Variable(random.random, trainable = True)
b = tf.Variable(random.random, trainable = True)

In [5]:
# loss
def simple_loss(y_act, y_pred):
    return tf.abs(y_act - y_pred)

In [6]:
LEARNING_RATE = 0.001

In [10]:
def fit_data(x_act, y_act):
    with tf.GradientTape(persistent=True) as tape:
        #prediction 
        y_hat = w*x_act + b
        
        #loss
        loss_cal = simple_loss(y_act, y_hat)
    
    # gradient calcualtion 
    w_gradient = tape.gradient(loss_cal, w)
    b_gradient = tape.gradient(loss_cal, b)
    
    
    #Update variable
    w.assign_sub(w_gradient * LEARNING_RATE)
    b.assign_sub(b_gradient * LEARNING_RATE)
    

In [11]:
# training loop
for _ in range(10):
    fit_data(x_train, y_train)
print(f'y = {w.numpy()}x + {b.numpy()}')

y = 0.9492853283882141x + 0.30743294954299927


In [12]:
#Normal training step
def train_step(images, labels):
    with tf.GradienTape() as tape:
        logits = model(images, training = True) #forward pass
        loss_value = loss_object(labels, logits)
    
    loss_history.append(loss_value.numpy().mean())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradient(zip(grads, model.trainable_variables))

# Calculating gradients of higher order tensors

In [13]:
x = tf.ones((2,2))

In [14]:
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [15]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.square(y)
dz_dx = t.gradient(z, x)

In [16]:
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [17]:
del t

# Nested Gradient

In [20]:
x = tf.Variable(1.0)
with tf.GradientTape() as tape_2:
    with tf.GradientTape() as tape_1:
        y = x*x*x
    
    dy_dx = tape_1.gradient(y, x)
d2y_d2x = tape_2.gradient(dy_dx, x)
    

In [21]:
d2y_d2x

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [22]:
x = tf.Variable(1.0)

with tf.GradientTape() as tape_2:
    with tf.GradientTape() as tape_1:
        y = x * x * x
    
        # The first gradient calculation can also be within the inner with block
        dy_dx = tape_1.gradient(y, x)
d2y_dx2 = tape_2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


#### Where not to indent the first gradient calculation
If the first gradient calculation is OUTSIDE of the outer `with` block, it won't persist for the second gradient calculation.

In [24]:
7*7+9*9+4*4+3*3

155

# Exercise

In [25]:
tmp_array = np.arange(1,10)

In [28]:
def tf_constant(array):
    """
    Args:
        array (numpy.ndarray): tensor-like array.

    Returns:
        tensorflow.python.framework.ops.EagerTensor: tensor.
    """
    ### START CODE HERE ###
    tf_constant_array = tf.constant([array])
    ### END CODE HERE ###
    return tf_constant_array

In [29]:
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>